### ISSUE TITLE
Undefined variable: wp_geometa_version

### ISSUE THREAD

**Issue by intelliweb** [BrilliantPlugins/wp-geometa-lib#6]
I'm getting the following...

Notice: Undefined variable: wp_geometa_version in public_html/wp-content/plugins/wp-geometa/lib/wp-geometa-lib/wp-geometa-lib.php on line 34

**Comment by nciske** [comment]
@intelliweb 

Thanks for reporting this.

Where are you seeing that error -- in debug.log and/or in site output?

Is it causing breakage (it shouldn't since it's just a notice)?

**Comment by nciske** [comment]
@stuporglue - Looks like a constant `WP_GEOMETA_VERSION` where `WP_GeoMeta::$version` should be used? Am I reading that right?

**Comment by intelliweb** [comment]
@nciske I saw it in site output. No, it's not causing breakage.

I'm actually using the WP-Geometa plugin which needs to be updated to the latest version of this library. It's throwing other errors. I managed to get those other errors fixed by editing the plugin but I think just updating the lib within the plugin would solve it.

**Comment by intelliweb** [comment]
@nciske - Any update on this?
